// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olqfuxcccoywxmxuacug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9scWZ1eGNjY295d3hteHVhY3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTgzMTYsImV4cCI6MjA2NTg3NDMxNn0.Yp3Dv5ukkYTL7CdE18_yD71ZdBsrC-GTQvMkfzWcaEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);